clear variables 
clc
close all
trise = 6; % sunrise time in 24 hour format
t = 0;
tset = 18; % sunset time in 24 hour format
time = 0:1:23;
Gsc = 1367; %Extraterrestrial solar radiation in W/m^2
n = 80; % nth day of the year
lat = 35.25; % Location latitude
del = 23.67 * (pi/180) * sin ((2*pi*284+n)/365.25); % declination angle calculation
omega = zeros(1,24);
for ts = 6:1:18
omega(ts) = (ts-12)*15; %hour angle
end
cos_zenith = cosd(lat)*cosd(del).*cosd(omega) + sind(lat)*sind(del); % zenith
G0n = Gsc * (1+0.033 * cos (360 * n / 365)); % Extra-terrestrial normal radiation 
G0 = G0n .* cos_zenith; % extra-terrestrial horizontal radiation
G0_max = max(G0);
for t = 1:1:24
if (t <= 7)
    i(t) = 0;
elseif (t>7 && t <= 18) 
    i(t) = G0_max * sin ( (pi * (t - trise))/(tset - trise)); %irradiance vector over time
elseif (t>19 && t <= 24)
    i(t) = 0;
end
end
% subplot(1,2,1);
plot (time, i)
xlabel ('time in hours');
ylabel (' Irradiance W/m^2');

Np = 2; % number of panels connected in parallel
Ns = 36; % number of cells connected in series in each panel
T = 298; % Surrounding temperature
Tref = 298; % Standard temperature
G = i;
Ki = 0.065; %temperature coefficient
Isc = 3.8; % short-circuit current in ampere
q = 1.602*10^-19; % value of charge in coulomb 
V_single = 0.6;% voltage generated by a single cell
Voc = Ns * V_single; % open circuit voltage in volts 
k = 1.381*10^-23; % Boltzmann's constant
A=1.3; % ideality factor
Eg = 1.12; % bandgap energy for polycrystalline Si at 25 degree C
Rs = 0.001*6; % series resistance
Rsh = 6000; %shunt resistance
Iph = (G .* (Ki * (T - Tref) + Isc ) ./ 1000); % photo current
Irs = Isc/(exp((Voc*q)/(Ns*A*k*T)) - 1); % reverse saturation current
Is = (T/Tref)^3*Irs*exp((Eg*q*(1/T - 1/Tref))/k*A); 
I = zeros(1,24);
for t = 1:1:24
    if (t <= 7)
        I(t) =0;
    elseif (t>7 && t<=18)
        I(t) = Np .* Iph(t) - Np * Is * (exp((Voc*q)/Ns*k*A*T) - 1) + ((Voc + I(t-1)*Rs)/Rsh);
    elseif (t>18 && t<=24)
        I(t) = 0;
    end
end
P =Voc .* I; % power generated in watts
% subplot(1,2,2);
plot (time, P,'r*');
xlabel('Time in hours');
ylabel('Power in W');
